---
name: La clase, el objeto y el mensaje
locale: es
type: learning
beta: false
teacher_info: ''
language: java
id_format: "%05d"
order:
- 20
- 1
- 2
- 3
- 4
- 19
- 5
- 6
- 8
- 9
- 16
- 10
- 17
- 14
- 13
- 18
private: false
