---
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: String
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: char
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: LocalDate
  checked: false
name: Tipos de todo tipo
