---
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "... declarar los atributos"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "... abrir y cerrar llaves en lugar de utilizar bloques terminados en end"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "... escribir los nombres de métodos en camelCase (deEstaForma)"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "... escribir los nombres de clases en snake_case (de_esta_otra_forma)"
  checked: false
name: Una introducción con clase
