---
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '... declarar "el tipo" de los atributos y métodos'
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "... poner punto y coma al final de algunas líneas"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "... escribir los nombres de clases en snake_case (de_esta_forma)"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "... escribir todo en inglés"
  checked: false
name: Una introducción con clase
